#pragma once
#ifndef  PRI_CORE_MAIN_H
#define PRI_CORE_MAIN_H

//MWM PRI core SW Version
#define MWM_PRI_CORE_SW_MAJOR_VERSION	1
#define MWM_PRI_CORE_SW_MINOR_VERSION	0
#define MWM_PRI_CORE_SW_BUGFIX_VERSION	0
#define MWM_PRI_CORE_SW_BUILD_VERSION	1

//MWM PRI core HW Version
#define MWM_PRI_CORE_HW_MAJOR_VERSION	1
#define MWM_PRI_CORE_HW_MINOR_VERSION	0
#define MWM_PRI_CORE_HW_BUGFIX_VERSION	0
#define MWM_PRI_CORE_HW_BUILD_VERSION	1

#endif // ! PRI_CORE_MAIN_H
